Fix error due to 'variably modified array at file scope'
This error happens because MAX_DEGREE was not a compile time integral
constant.

src/lib/GeoRef_Type_Q.c:13:21: error: variably modified ‘QUAD_POINTS’ at file scope
   13 | static const double QUAD_POINTS[MAX_DEGREE + 1][MAX_DEGREE + 1] = {
      |                     ^~~~~~~~~~~